version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: devsync-postgres
    restart: always
    environment:
      POSTGRES_USER: devsync
      POSTGRES_PASSWORD: devsync123
      POSTGRES_DB: devsync_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
